# Generated by Django 5.1.15 on 2026-05-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
